fastlane_bot/events/managers/manager.py
We need to test if this fixes the issue, however it requires a Strategy Deleted event to check.
=> move strategy deleted event to be with other Carbon events

fastlane_bot/events/exchanges/carbon_v1.py
Added a check before trying to delete a strategy that may or may not exist
=> Fix for strategy deleted event

fastlane_bot/helpers/txhelpers.py
The missing `return` statement leads to an attempt to use the non-initialized variable named `transaction`.
=> Return `None` when the 2nd call to `construct_contract_function` fails

fastlane_bot/events/async_event_update_utils.py
…erly handled
- Carbon cid values are provided by the contract and are int types, whereas all other exchange cid values are generated by hashing the descr (exchange tkn1/tkn2 fee) info.
- This fix ensures that the types and values of carbon cid's are preserved
- This change is also believed to be a fix for the seemingly unrelated `Ox string without prefix` error
=> hex string without 0x prefix

fastlane_bot/events/utils.py, fastlane_bot/utils.py, run_blockchain_terraformer.py, test_get_start_block.py
If the `last_updated_block` column contains `None` values, then `max` returns a value of type `float`.
The caller should therefore verify that this value is nevertheless integer, and then convert it to type `int`.
Note that this PR also includes a technical refactoring of function `get_start_block`, aimed at simplifying the logical flow in this function, as well as the removal of log messages in this function (which were designated for the investigation of the non-integer-block-number issue).
=> Fix the calculation of a non-integer block number

.github/workflows/run-pytest.yml, NBTest_068_exceptions.py, fastlane_bot/events/async_event_update_utils.py, fastlane_bot/events/async_utils.py, fastlane_bot/events/exceptions.py, fastlane_bot/events/pools/solidly_v2.py, main.py, resources/NBTest/NBTest_068_exceptions.py, resources/NBTest/NBTest_908_run_async_update_with_retries.py
This PR addresses the issue:
https://github.com/bancorprotocol/fastlane-bot/issues/331
The bug occurred in async_event_update_utils.py specifically for Solidly-fork exchanges. 
The issue was that Solidly forks require the Factory contract to get the pool's fee, and when get_fee was called in the function get_token_and_fee, the exchange object had not been properly initialized with its factory contract. I changed the function to use the exchange object that was already initialized on startup, stored in Manager base.py.
=> 331 trading on aerodrome v2 is not properly supported

fastlane_bot/bot.py, fastlane_bot/events/managers/base.py
Initialized Solidly Factory contracts using web3 async instead of web3, which was causing Solidly pools to fail to fetch fees in the async function.
=> 337 failed to get tokens and fee for aerodrome v2

fastlane_bot/helpers/txhelpers.py, fastlane_bot/tools/pool_shutdown.py
=> Revise all submit-transaction methods in the TxHelpers module

fastlane_bot/config/constants.py, fastlane_bot/config/network.py, fastlane_bot/helpers/routehandler.py
These exchanges on Mantle use Uniswap V3 Router 01:
-butter_v3
-agni_v3
This change adds the exchanges to the list of exchanges that should use Router 01 in the `handle_custom_data_extras` function in routehandler.py.
=> Add handling for specific Uni V3 exchanges on Mantle

fastlane_bot/tests/test_072_TestTerraformer.py, run_blockchain_terraformer.py
The PR that this branch is based on introduced the "strategy_id" field into the static data (and Pool class) data structure. This field is only applicable for Carbon pools, and is set to 0 for all other pools to maintain consistent typing (int). This change to the Terraformer adds the missing field when pool data is generated.
I have added a corresponding test that ensures that this field is set for the four main data processing functions in the Terraformer. These tests can be expanded further into a test suite for the Terraformer, however, that is out of the scope of this PR.
=> Add strategy_id to terraformer

fastlane_bot/events/managers/base.py, fastlane_bot/helpers/txhelpers.py
This fixes a critical error in the `build_transaction_generic` function. The `**kwargs` were mistakenly passed into the contract function instead of the `build_tx` function in cases in which the initial gas base fee was wrong, causing it to fail.
I have verified that transactions are able to be constructed after this change.
=> Fix args kwargs usage in build transaction generic

fastlane_bot/events/pools/solidly_v2.py, fastlane_bot/events/pools/uniswap_v2.py, fastlane_bot/events/pools/uniswap_v3.py
Removed call to fetch Factory address for Solidly V2 pools as the value was unused.
=> Removed Factory address call for Solidly V2 pools

fastlane_bot/data/abi.py, fastlane_bot/events/exchanges/solidly_v2.py, fastlane_bot/tests/test_037_Exchanges.py
1. Remove functions `factory` and `voter` from pool contract ABIs
2. Remove the Velocimeter-V2 ABI and use the Solidly-V2 ABI instead
=> Clean ABIs following the removal of the factory address retrieval

fastlane_bot/bot.py, fastlane_bot/events/utils.py, fastlane_bot/helpers/__init__.py, fastlane_bot/helpers/routehandler.py, fastlane_bot/tests/test_039_TestMultiMode.py, fastlane_bot/tests/test_040_TestSingleMode.py, fastlane_bot/tests/test_042_TestBancorV3ModeTwoHop.py, fastlane_bot/tests/test_043_TestEmptyCarbonOrders.py, fastlane_bot/tests/test_045_Validator.py, fastlane_bot/tests/test_047_Randomizer.py, fastlane_bot/tests/test_050_TestBancorV2.py, fastlane_bot/tests/test_053_TknMaxTrade.py, fastlane_bot/tests/test_060_TestRoutehandlerCarbonPrecision.py, fastlane_bot/tests/test_061_TestWETHConversion.py, fastlane_bot/tests/test_063_TestBancorPOLMode.py, fastlane_bot/tests/test_064_TestMultiAllMode.py, fastlane_bot/tests/test_901_TestMultiTriangleModeSlow.py, fastlane_bot/utils.py, main.py
This is a preliminary step for moving the initialization of the bot out of the main loop, which may help in significantly reducing the duration of each iteration in that loop (see issue #560).
=> Module bot cleanup

fastlane_bot/bot.py, fastlane_bot/events/managers/manager.py, fastlane_bot/events/utils.py, fastlane_bot/tests/test_037_Exchanges.py
1. Remove unused function `Manager.update_from_contract`
2. Remove redundant return-value in function `Manager.update_from_pool_info`
3. Redeclare optional input argument `pool_info` as mandatory in function `Manager.update_from_pool_info`
4. Remove unused input argument `event`, `address`, `token_address` and `contract` in function `Manager.update`
5. Remove recursive call in function `Manager.update`, since the infinite `while` loop can (and should) handle this
=> Clean the `manager` module

fastlane_bot/helpers/txhelpers.py
Partially handles issue #556:
- Still need to verify that it works with flashbots
- Still need to check if it works with mevblocker
- Still need to re-enable `self.use_access_list`
=> Refrain from including the access-list when it contains an error

fastlane_bot/tools/cpc.py, fastlane_bot/tools/optimizer/margpoptimizer.py, fastlane_bot/tools/simplepair.py, resources/NBTest/NBTest_002_CPCandOptimizer.ipynb, resources/NBTest/NBTest_002_CPCandOptimizer.py, resources/NBTest/NBTest_003_Serialization.ipynb, resources/NBTest/NBTest_003_Serialization.py
This is an early commit of settled features within the #588 and #253 pull requests. It introduces potentially significant changes under the hood. I do not expect things to fail -- and tests don't -- but this is big enough to warrant a certain period of testing
Major changes
- Optimizer now allows for absolute convergence checks; those improve convergence but requires USD rates; by default they are disabled
- CPC.from_carbon  on constant price curves now produces slightly more convex curves for better numeric stability; **this can have knock on effects**
- there is a trivial change to SimplePair that should not affect anything
=> Optimizer5.3 (partial commit of convergence 2)

fastlane_bot/tests/test_039_TestMultiMode.py
Test 39 should assert the number of curves in the dataset to avoid silent conversion fails
(note this test will fail in PR #610)
=> Fixing test 39 (silent fails of curve conversion)

fastlane_bot/helpers/poolandtokens.py, fastlane_bot/utils.py
**MUST BE MERGE INTO #606 ASAP**
Overlapping strategies are designed to recreate Uniswap v3 like strategies on Carbon, ie ranges that trade bidirectional taking a small fee. Unsurprisingly -- in hindsight -- those strategies behave as badly within the Optimizer as other strategies with fees would (see #588). There is a reason that we ignore fees in the Optimizer and add them back only in the fine tuning step. 
High level the solution is actually pretty easy: **remove the effective fee component from overlapping strategies**. The current PR is designed to achieve that. However, it is a bit hacky, and once we have time we need to also take into account a few considerations spelled out in the next comment
=> Convergence issues with overlapping strategies

fastlane_bot/config/network.py, fastlane_bot/events/interface.py, fastlane_bot/events/utils.py, fastlane_bot/tests/test_034_Interface.py, main.py
Replacement for #624 since there were some merge mistakes there
Handles issues #626 and #592
=> Fixes handling of flashloan tokens and target tokens where addresses can get dropped

fastlane_bot/bot.py, fastlane_bot/modes/base_pairwise.py, fastlane_bot/modes/base_triangle.py, fastlane_bot/modes/pairwise_multi_all.py, fastlane_bot/modes/triangle_multi_complete.py, fastlane_bot/tests/test_064_TestMultiAllMode.py, main.py
- Added specific support for carbon only curves in the multi_pairwise_all (may break tests due to more arbs)
- Expanded the scope of combos (may break tests due to more arbs)
- Added new mode to improve coverage of carbon-centric triangles (new tests tbd)
=> 401 add support for intra and inter carbon deployment arbs

fastlane_bot/modes/base_triangle.py, fastlane_bot/modes/triangle_multi.py, fastlane_bot/modes/triangle_multi_complete.py, fastlane_bot/tests/test_064_TestMultiAllMode.py
1. Remove `@staticmethod` decorator from several global-scope functions (bug fix)
2. Remove unused input argument `arb_mode` in function `get_comprehensive_triangles` (enhancement)
3. Fix the handling of trade instructions in function `ArbitrageFinderTriangleMulti.find_arbitrage` (bug fix)
4. Fix the handling of trade instructions in function `ArbitrageFinderTriangleMultiComplete.find_arbitrage` (bug fix)
5. Fix and reinstate (uncomment) an assertion in test 064 (enhancement)
6. Fix function `build_pstart` in class `ArbitrageFinderTriangleBase`, and remove that function in each one of the classes which inherits that class (bug fix)
=> Fix several issue in the triangle-mode implementation

fastlane_bot/modes/triangle_multi_complete.py
Carbon curves should be collected by their direction (i.e. the token that they are selling) to prevent downstream failures building the route
=> handle curve direction triangle complete
