fastlane_bot/__init__.py

Bump version [skip ci]

---

setup.py

Fix Github Link

---

run_pool_shutdown.py

Reverts bancorprotocol/fastlane-bot#182

Revert "adds base_path to the get_static_data fn"

---

fastlane_bot/modes/triangle_multi.py

updated from using base/quote to using the correct x/y

bugfix pstart

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature_request.md

Update issue templates

---

fastlane_bot/events/exchanges/solidly_v2.py
run_blockchain_terraformer.py

Fixed Velocimeter Fee calculation + small code cleanup.

Clean up Solidly fee calculations

---

fastlane_bot/config/constants.py
fastlane_bot/events/exchanges/uniswap_v3.py
fastlane_bot/events/managers/base.py

Agni V3 is a fork of Pancakeswap V3. 
I changed its handling to reflect that & changed hardcoded strings to constants.

Change Agni to Pancakeswap fork handling

---

.env.example
README.md
fastlane_bot/config/network.py

Changed default RPC provider for Mantle in network.py and added commented link to provider's website.

Change default RPC provider for Mantle

---

fastlane_bot/events/async_event_update_utils.py

Fixes a bug in the get_tokens_and_fee function which tries to access a variable that wasn't created (due to name changes) - (i.e. it breaks the bot).

bugfix for get_tokens_and_fee issues

---

fastlane_bot/helpers/poolandtokens.py

Fix issue 509

---

fastlane_bot/events/managers/pools.py

Bugfix for issue: https://github.com/bancorprotocol/fastlane-bot/issues/521

Hotfix - Carbon strategies duplicated

---

README.md
fastlane_bot/bot.py
fastlane_bot/config/provider.py
fastlane_bot/data/abi.py
fastlane_bot/events/multicall_utils.py
fastlane_bot/events/pools/bancor_pol.py
fastlane_bot/tests_on_hold/test_907_RuntimeParameters.py
main.py

Get rid of checking arb-contract version

---

fastlane_bot/bot.py
fastlane_bot/helpers/__init__.py
fastlane_bot/helpers/poolandtokens.py

Gracefully handle solidly stable pools not supported errors

---

resources/NBTest/NBTest_002_CPCandOptimizer.ipynb
resources/NBTest/NBTest_002_CPCandOptimizer.py
resources/NBTest/NBTest_900_OptimizerDetailedSlow.ipynb
resources/NBTest/NBTest_900_OptimizerDetailedSlow.py

Remove time-assertions in various tests

---

resources/NBTest/NBTest_900_OptimizerDetailedSlow.ipynb
resources/NBTest/NBTest_900_OptimizerDetailedSlow.py
resources/NBTest/test_900_OptimizerDetailedSlow.py

this comments out the convex optimizer code that is not used in prod and that seems to be unreliable when testing on github

Test900 fails

---

.github/workflows/release-and-pypi-publish.yml
databricks.sh

Added databricks init script
Fixed a bug in CI

feat: databricks init script

---

resources/NBTest/OptimizerTesting.ipynb
resources/NBTest/OptimizerTesting.py

adds a notebook for optimizer testing; no other effects
Note: the notebook itself may or may not run at this stage; it has been produced after the changes in #588. 
Therefore
- this PR must include 76880bc7c23b1f1d1108f8297c785b811abbe4c8 (no rebase / rewrite)
- it must be merged before #588 
- it should be merged before #253

OptimizerTesting

---

fastlane_bot/config/multicaller.py

Fix issue 584 in multicaller.py

---

fastlane_bot/events/async_event_update_utils.py

Fix `last_updated_block` key error

---

fastlane_bot/tools/optimizer/cpcarboptimizer.py
resources/NBTest/NBTest_101_CPCOptimizerNewFeatures.ipynb
resources/NBTest/NBTest_101_CPCOptimizerNewFeatures.py

fixing this bug
@stefan538 - Can you please look into this line in your code:
https://github.com/bancorprotocol/fastlane-bot/blob/Optimizer-CPC/fastlane_bot/tools/optimizer/cpcarboptimizer.py#L98

Optimizer bugfix

---

fastlane_bot/events/async_event_update_utils.py

Fix function `async_update_pools_from_contracts`

---

fastlane_bot/events/pools/bancor_pol.py

This is a temporary solution to POL support while multicall is reverting

focus the pol to ETH only temp solve multicall

---

fastlane_bot/events/pools/bancor_pol.py

Reverts bancorprotocol/fastlane-bot#643

Revert "focus the pol to ETH only temp solve multicall"

---

fastlane_bot/modes/base_triangle.py
fastlane_bot/modes/triangle_multi_complete.py

Reverts bancorprotocol/fastlane-bot#684

Revert "Add triangle_multi_complete mode"
